My_blog/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.views.static import serve
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from users.views import register, logIn, logOut, DeleteUserView, ProfileView, EditProfile, FollowView, PasswordsChangeView
# from myblog.sitemaps import StaticViewsSitemap,PostSitemap,ProfileSitemap
# from django.contrib.sitemaps.views import sitemap

# sitemaps = {
#     'sitemap':StaticViewsSitemap,
#     'posts':PostSitemap,
#     'profile':ProfileSitemap,
# }

urlpatterns = [
    # path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
    #  name='django.contrib.sitemaps.views.sitemap'),
    re_path(r'^media/(?P<path>.+)$',serve,{'document_root':settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
    path('admin/', admin.site.urls),
    path('register/', register, name='register'),
    path('login/', logIn, name='login'),
    path('logout/', logOut, name='logout'),
    path('profile/aaa235423<int:pk>5kfjsdlaaa/',ProfileView.as_view(),name='profile'),
    path('profile/delete/aaa235423<int:pk>5kfjsdlaaa/',DeleteUserView.as_view(), name='delete_user' ),
    path('edit_profile', EditProfile, name='edit_profile'),
    path('follow/<int:pk>', FollowView, name='follow_user'),
    path('password/',PasswordsChangeView.as_view(), name='password'),
    path('reset_password/',auth_views.PasswordResetView.as_view(template_name='users/reset_password.html'), name='reset_password'),
    path('reset_password_sent/',auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_sent.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_form.html'), name='password_reset_confirm'),
    path('reset_password_complete/',auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_done.html'), name='password_reset_complete'),
    path('',include('myblog.urls')),
    path('ckeditor', include('ckeditor_uploader.urls')),


]

# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myblog/urls.py
from django.urls import path, include
from .views import HomeView, BlogDetialView, Search, Joinus, CatList, FavPostView, FavCatView, Privacy ,UserNotification, Aboutus ,Contact, CategoryView, AddPostView, AddCategory, UpdatePostView, DeletePostView, LikeView



urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('about/', Aboutus, name='about'),
    path('privacy_policy/', Privacy, name='privacy'),
    path('notification/', UserNotification, name='notification'),
    path('addpost/', AddPostView.as_view(), name='addpost'),
    path('blog/read=da212ijna<int:pk>1edsdjh', BlogDetialView.as_view(), name='blog'),
    path('category/<str:cats>', CategoryView, name='cat'),
    path('addcat',AddCategory.as_view(), name='addcat'),
    path('search/', Search, name='search'),
    path('contact/', Contact, name='contact'),
    path('joinus/', Joinus, name='joinus'),
    path('blog/edit/<int:pk>', UpdatePostView.as_view(), name='update_post'),
    path('blog/delete/<int:pk>', DeletePostView.as_view(), name='delete_post'),
    path('like/<int:pk>',LikeView,name='like_post'),
    path('favcat/<str:cats>',FavCatView, name='fav_cat'),
    path('favpost/<int:pk>',FavPostView, name='fav_post'),
    path('category/',CatList, name='cat_list'),
    path('hitcount/', include(('hitcount.urls', 'hitcount'), namespace='hitcount')),

]

Notifications/models.py
from django.db import models
from django.contrib.auth.models import User
from myblog.models import Post
from django.utils import timezone

class Notification(models.Model):
    NOTIFICATION_TYPE =((1,'like'),(2,'comment'),(3,'follow'),(4,'add post'),(5,'update post'),(0,'fav cat'))

    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="post", blank=True, null=True)
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sender')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='reciver')
    notification_type = models.IntegerField(choices=NOTIFICATION_TYPE)
    date = models.DateTimeField(default=timezone.now)
    is_seen = models.BooleanField(default=False)

    def __str__(self):
        return  f"Notification to {self.user}"

myblog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
from hitcount.models import HitCountMixin, HitCount
from django.contrib.contenttypes.fields import GenericRelation
from taggit.managers import TaggableManager


class Category(models.Model):
    cat_name = models.CharField(max_length=255,unique=True)
    cat_img = models.ImageField(default='default_thumb.jpg',upload_to='category',blank=True)
    cat_view = GenericRelation(HitCount, object_id_field='object_pk', related_query_name='hit_count_generic_relation')
    
    def __str__(self):
        return self.cat_name
    
    def get_absolute_url(self):
        return reverse('home')

class Post(models.Model):
    thumbnail = models.ImageField(default='default_thumb.jpg',upload_to='thumbnail',blank=True)
    title = models.CharField(max_length=255)
    post_tag = TaggableManager()
    cat = models.CharField(Category,max_length=100, default="None")
    content = RichTextUploadingField(blank=True, null=True)
    hit_count_generic = GenericRelation(HitCount, object_id_field='object_pk',related_query_name='hit_count_generic_relation')
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User,on_delete=models.CASCADE)
    likes = models.ManyToManyField(User,related_name='blog_like')

    def total_likes(self):
        return self.likes.count()

    
    def __str__(self):
        return self.title + ' | ' + str(self.author)
    
    def get_absolute_url(self):
        return reverse('blog', args=[self.id,])



class Comment(models.Model):
    post = models.ForeignKey(Post, related_name = "comments", on_delete=models.CASCADE)
    name = models.ForeignKey(User,on_delete=models.CASCADE)
    body = models.TextField()
    date = models.DateTimeField(default=timezone.now)


    def __str__(self):
        return  '%s - %s - %s' % (self.post.title, self.name, self.body)
    


    

myblog/forms.py
from django import forms
from .models import Post, Category, Comment
from community.models import JoinUs


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'cat', 'post_tag', 'thumbnail', 'content','author']

        widgets = {
            'author': forms.TextInput(attrs={'class':'form-control','placeholder':'Author','value':'','id':'user','type':'hidden'}),

        }
class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = '__all__'

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name','body']

class PostUpdateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title','content','thumbnail']

class JoinUsForm(forms.ModelForm):
    class Meta:
        model = JoinUs
        fields = '__all__'
 

Notifications/views.py
from django.shortcuts import render

# Create your views here.

myblog/views.py
from django.shortcuts import render, get_object_or_404, redirect, reverse   
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Post, Category, Comment
from community.models import JoinUs
from .forms import PostForm, CategoryForm, CommentForm, PostUpdateForm, JoinUsForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse
from django.http import HttpResponseRedirect, HttpResponse
from hitcount.views import HitCountDetailView
from hitcount.utils import get_hitcount_model
from hitcount.views import HitCountMixin
from django.core.mail import send_mail
from django.conf import settings
from Notifications.models import Notification
from users.models import Profile
from django.contrib.auth.models import User
from django.core.paginator import Paginator


class HomeView(ListView):
    model = Post
    paginate_by = 6
    template_name = 'blog/home.html'
    ordering = ['-date_posted']

    def post(self, request, *args, **kwargs):
        if request.method == "POST":
            id = request.POST.get('id')
            user = request.POST.get('user')
            if id:
                note = get_object_or_404(Notification, id=id)
                note.is_seen = True
                note.save()
            if user:
                notes = Notification.objects.filter(user=user)
                for note in notes:
                    note.is_seen = True
                    note.save()
        return redirect(request.META.get('HTTP_REFERER', 'redirect_if_referer_not_found'))

    def get_context_data(self, *args, **kwargs):
        notification = Notification.objects.filter(user=self.request.user.id, is_seen=False).order_by('-date')  
        cat_tab = Category.objects.all().order_by('cat_view')[:9]
        pop_posts = Post.objects.all().order_by('hit_count_generic')[:5]
        context = super(HomeView, self).get_context_data(*args, **kwargs)
        context['cat_tab'] = cat_tab
        context['pop_posts'] = pop_posts
        context['notification'] = notification
        context['active1'] = 'nav-active'
        return context 

def Aboutus(request):
    if request.user.is_authenticated:
        notification = Notification.objects.filter(user=request.user, is_seen=False).order_by('-date') 
    else:
        notification = None  
    post = Post.objects.all().count()
    user = User.objects.all()
    cat_tab = Category.objects.all()[:10]
    community = JoinUs.objects.all()
    if post == 0:
        pst = 0 
    else:
        pst = post.count()
 
    context = {
        'post':pst,
        'usr':user,
        'com':community,
        'notification':notification,
        'cat_tab':cat_tab,
    }
    return render(request,'blog/aboutus.html', context)

def Privacy(request):
    if request.user.is_authenticated:
        notification = Notification.objects.filter(user=request.user, is_seen=False).order_by('-date') 
    else:
        notification = None
    cat_tab = Category.objects.all()[:10]
    context = {
            'cat_tab':cat_tab,
            'notification':notification,
    }
    return render(request,'blog/privacypolicy.html',context)

class BlogDetialView(HitCountDetailView,DetailView):
    model = Post
    template_name = 'blog/blogview.html'
    form = CommentForm
    count_hit = True

    def post(self, request, *args, **kwargs):
        form = CommentForm(request.POST)
        post = self.get_object()
        if form.is_valid():
            form.instance.post = post
            form.instance.name = request.user
            form.save()
            if request.user != post.author:
                note = Notification(notification_type=2, post=post, sender=request.user, user=post.author)
                note.save()
        return redirect(request.META.get('HTTP_REFERER', 'redirect_if_referer_not_found'))

    def get_context_data(self, *args, **kwargs):
        cat_tab = Category.objects.all()[:10]
        similar_post = self.object.post_tag.similar_objects()[:5]
        context = super(BlogDetialView, self).get_context_data(*args, **kwargs)
        stuff = get_object_or_404(Post, id=self.kwargs['pk'])
        post_filter = Post.objects.filter(author=stuff.author).order_by('hit_count_generic')[:10]
        total_likes = stuff.total_likes()
        liked_user = stuff.likes.all()
        liked = False
        followed = False
        added = False
        if self.request.user.is_authenticated:
            pro_stuff = get_object_or_404(Profile, id=self.request.user.id)
            if stuff.likes.filter(id=self.request.user.id).exists():
                liked = True
            if pro_stuff.following.filter(id=stuff.author.id):
                followed = True
            if pro_stuff.fav_post.filter(id=stuff.id):
                added=True
            notification = Notification.objects.filter(user=self.request.user, is_seen=False).order_by('-date')  
            context['notification'] = notification
        context["total_likes"] = total_likes
        context["similar_post"] = similar_post
        context['liked_user'] = liked_user
        context['added'] = added
        context['liked'] = liked
        context['followed'] = followed
        context['form'] = self.form
        context["post_filter"] = post_filter
        context["cat_tab"] = cat_tab
        context["title"] = stuff.title
        return context 

def CategoryView(request, cats):
    cat = get_object_or_404(Category, cat_name=cats)
    fav_cat_user = Profile.objects.filter(fav_cat=cat.id)
    added = False
    if request.user.is_authenticated:
        notification = Notification.objects.filter(user=request.user, is_seen=False).order_by('-date') 
        stuff = get_object_or_404(Profile, id=request.user.id)
        if stuff.fav_cat.filter(id = cat.id):
            added = True
    else:
        notification=None
    cat_tab = Category.objects.all()[:10]
    category_post = Post.objects.filter(cat=cats).order_by('-date_posted')
    # paginator = Paginator(category_post, 8) 
    # page_number = request.GET.get('page')
    # page_obj = paginator.get_page(page_number)
    context = {
        'title':cats,
        'notification':notification,
        # 'page_obj': page_obj, 
        'added':added,
        'cat_tab':cat_tab,
        'cat_post':category_post,
        'fav_cat_user':fav_cat_user,
    }
    # hitcount logic
    hit_count = get_hitcount_model().objects.get_for_object(cat)
    hits = hit_count.hits
    hitcontext = context['hitcount'] = {'pk': hit_count.pk}
    hit_count_response = HitCountMixin.hit_count(request, hit_count)
    if hit_count_response.hit_counted:
        hits = hits + 1
        hitcontext['hit_counted'] = hit_count_response.hit_counted
        hitcontext['hit_message'] = hit_count_response.hit_message
        hitcontext['total_hits'] = hits
    return render(request, 'blog/category.html', context)

def CatList(request):
    cat = Category.objects.all()
    cat_tab = Category.objects.all()[:10]
    if request.user.is_authenticated:
        notification = Notification.objects.filter(user=request.user, is_seen=False).order_by('-date') 
    else:
        notification=None
    context = {
        'cat':cat, 
        'notification':notification, 
        'title':"Category",
        'cat_tab':cat_tab
        }
    return render(request, 'blog/categoryList.html', context)

class AddPostView(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostForm
    template_name = 'blog/add_post.html'
    login_url = 'login'

    def post(self, request, *args, **kwargs):
        form = PostForm(request.POST)
        if form.is_valid():
            cat = Category.objects.get(cat_name=request.POST.get('cat')) 
            post = form.save()
            fav_cat_user = Profile.objects.filter(fav_cat=cat)
            for user in fav_cat_user:
                if user.user is not request.user:
                    note = Notification(notification_type=6, post=post, sender=request.user, user=user.user)
                    note.save()
            field_name = 'followers'
            obj = Profile.objects.get(id=request.user.profile.id)
            field_object = Profile._meta.get_field(field_name)
            follower = field_object.value_from_object(obj)
            for user in follower:
                note = Notification(notification_type=4, post=post, sender=request.user, user=user)
                note.save()
        return redirect(reverse('blog', args=[str(post.pk)]))
        
    def get_context_data(self, *args, **kwargs):
        cat = Category.objects.all()
        cat_tab = Category.objects.all()[:10]
        notification = Notification.objects.filter(user=self.request.user, is_seen=False).order_by('-date') 
        context = super(AddPostView, self).get_context_data(*args, **kwargs)
        context["title"] = 'New Post'
        context['cat_tab'] = cat_tab
        context['cat'] = cat
        context['notification'] = notification
        context['active2'] = 'nav-active'
        return context


class AddCategory(LoginRequiredMixin, CreateView):
    model = Category
    template_name = 'blog/add_category.html'
    fields = '__all__'
    login_url = 'login'
    
    def get_context_data(self, *args, **kwargs):
        cat_tab = Category.objects.all()[:10]
        notification = Notification.objects.filter(user=self.request.user, is_seen=False).order_by('-date') 
        context = super(AddCategory, self).get_context_data(*args, **kwargs)
        context["title"] = 'Add Category'
        context['notification'] = notification
        context['cat_tab'] = cat_tab
        return context

    def get_success_url(self):
        return reverse('addpost')

def Search(request):
    if request.user.is_authenticated:
        notification = Notification.objects.filter(user=request.user, is_seen=False).order_by('-date') 
    else:
        notification = None    

myblog/templates/blog/aboutus.html
{% extends 'blog/index.html' %}
{% load static %}
{% load hitcount_tags %}
{% block content %}
<div class="container fs">
    <div class="about">
        <h1 class="text-center">About Us</h1>
        <p style="text-align: center;">
            <b>KnowNow</b> is a Professional blogging platform to share and enhance your knowledge. Here you can share interesting content you know and gain your knowledge on your domain.We're dedicated to providing you the best , with a focus on dependability .We're working to feed you interesting contents everyday and enhance your knowledge. We hope you enjoy our blogging as much as we enjoy offering them to you. Keep sharing your thoughts. Provide us your support and <i style="color:Red;" class="fa fa-heart"></i> love.
        </p>
    <div class="team-grid">
        <div class="container">
            <div class="intro">
                <h2 class="text-center">Founders</h2>
            </div>
            <div class="row people">
                <div class="col-md-4 col-lg-4 item">
                    <div class="box" style="background-image:url(/static/blog/img/sabari.jpg)">
                        <div class="cover">
                            <h3 class="name">Sabari Ravikumar</h3>
                            <!-- <p class="title">Founder and ceo</p> -->
                            <div class="social"><a href="https://www.linkedin.com/in/sabari-ravi-08b9a9190/" target="_blank"><i class="fa fa-linkedin"></i></a><a href="https://www.facebook.com/profile.php?id=100008793161481" target="_blank"><i class="fa fa-facebook-official"></i></a><a href="https://twitter.com/sabariravikuma2" target="_blank"><i class="fa fa-twitter"></i></a><a href="https://www.instagram.com/sabariravikumar/" target="_blank"><i class="fa fa-instagram"></i></a></div>
                        </div>
                    </div>
                </div>
                <div class="col-md-5 col-lg-4 item">
                    <div class="box" style="background-image:url(/static/blog/img/gowtham.jpeg)">
                        <div class="cover">
                            <h3 class="name">Gowtham Vishal</h3>
                            <!-- <p class="title">Co-Founder</p> -->
                            <div class="social"><a href="https://www.linkedin.com/in/gowtham-vishal-s-a-a22099192/" target="_blank"><i class="fa fa-linkedin"></i></a><a href="https://www.facebook.com/profile.php?id=100012294574290" target="_blank"><i class="fa fa-facebook-official"></i></a><a href="#"><i class="fa fa-twitter"></i></a><a href="https://www.instagram.com/gowtham_jack_jr_/" target="_blank"><i class="fa fa-instagram"></i></a></div>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 col-lg-4 item">
                    <div class="box" style="background-image:url(/static/blog/img/sooriya.jpg)">
                        <div class="cover">
                            <h3 class="name">Sri Soorya sivakumar</h3>
                            <!-- <p class="title">Co-Founder </p> -->
                            <div class="social"><a href="https://www.linkedin.com/in/sri-soorya-sivakumar-86198018b/" target="_blank"><i class="fa fa-linkedin"></i></a><a href="https://www.facebook.com/sri.soorya.1" target="_blank"><i class="fa fa-facebook-official"></i></a><a href="https://twitter.com/_sri_14_?s=09" target="_blank"><i class="fa fa-twitter"></i></a><a href="https://www.instagram.com/soorya.14/" target="_blank"><i class="fa fa-instagram"></i></a></div>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 col-lg-4 item">
                    <div class="box" style="background-image:url(/static/blog/img/harish.jpg)">
                        <div class="cover">
                            <h3 class="name">Harish Vijayan</h3>
                            <!-- <p class="title">director</p> -->
                            <div class="social"><a href="https://www.linkedin.com/in/harish-v-046a8618b/" target="_blank"><i class="fa fa-linkedin"></i></a><a href="https://www.facebook.com/profile.php?id=100004906756047" target="_blank"><i class="fa fa-facebook-official"></i></a><a href="https://twitter.com/Harish2651?s=08" target="_blank"><i class="fa fa-twitter"></i></a><a href="https://www.instagram.com/harish_vjn/" target="_blank"><i class="fa fa-instagram"></i></a></div>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 col-lg-4 item">
                    <div class="box" style="background-image:url(/static/blog/img/mugunthan.jpeg)">
                        <div class="cover">
                            <h3 class="name">Mugunthan</h3>
                            <!-- <p class="title">cto</p> -->
                            <div class="social"><a href="https://www.linkedin.com/in/mugunthan-a-043a72174" target="_blank"><i class="fa fa-linkedin"></i></a><a href="https://www.facebook.com/abinav.mugunthan.5"><i class="fa fa-facebook-official"></i></a><a href="https://twitter.com/Mugunthan_11?s=08" target="_blank"><i class="fa fa-twitter"></i></a><a href="https://www.instagram.com/m.u.g.u.n.t.h.a.n/" target="_blank"><i class="fa fa-instagram"></i></a></div>
                        </div>
                    </div>
                </div>
                <div class="col-md-5 col-lg-4 item">
                    <div class="box" style="background-image:url(/static/blog/img/jeevaa.jpg)">
                        <div class="cover">
                            <h3 class="name">Jeevaa</h3>
                            <!-- <p class="title">Content Creator</p> -->
                            <div class="social"><a href="https://www.linkedin.com/in/jeevaa-d-4307311b6/" target="_blank"><i class="fa fa-linkedin"></i></a><a href="#"><i class="fa fa-facebook-official"></i></a><a href="" target="_blank"><i class="fa fa-twitter"></i></a><a href="https://www.instagram.com/jeevaa21/" target="_blank"><i class="fa fa-instagram"></i></a></div>
                        </div>
                    </div>
                </div>
 
            </div>
        </div>
    </div>
    <div class="features-boxed" data-aos="fade-up">
        <div class="container">
            <div class="intro">
                <h2 class="text-center">Features </h2>
            </div>
            <div class="row justify-content-center features">
                <div class="col-sm-6 col-md-5 col-lg-4 item">
                    <div class="box"><i class="fa fa-book icon"></i>
                        <h1 id="post">{{post}}</h1>
                        <h3 class="name">Posts</h3>
                    </div>
                </div>
                <div class="col-sm-6 col-md-5 col-lg-4 item">
                    <div class="box"><i class="fa fa-user icon"></i>
                        <h1 id="user">{{usr.count}}</h1>
                        <h3 class="name">User</h3>
                    </div>
                </div>
                <div class="col-sm-6 col-md-5 col-lg-4 item">
                    <div class="box"><i class="fa fa-users icon"></i>
                        <h1 id="visitors">{{com.count}}</h1>
                        <h3 class="name">Our Community</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    var post = setInterval(PostCount, 50)
    var user = setInterval(UserCount, 50)
    var visit = setInterval(VisitCount, 50)
    let count1 = 0;
    let count2 = 0;
    let count3 = 0;

    function PostCount(){
        count1++;
        document.querySelector("#post").innerHTML = count1;
        if (count1 == "{{post.count}}"){
            clearInterval(post)
        }
    }
    function UserCount(){
        count2++;
        document.querySelector("#user").innerHTML = count2;
        if (count2 == "{{usr.count}}"){
            clearInterval(user)
        }
    }
    function VisitCount(){
        count3++;
        document.querySelector("#visitors").innerHTML = count3;
        if (count3 == "{{com.count}}"){
            clearInterval(visit)
        }
    }
</script>
{% endblock content %}

myblog/templates/blog/add_category.html
{% extends 'blog/index.html' %}
{% load static %}
{% block content %}

<div class="login-clean container">
    <form data-aos="fade-left" enctype="multipart/form-data" data-aos-delay="600" method="post" novalidate>
        {% csrf_token %}
        <div class="form-row">
            <div class="form-group col-md-6" style="margin-left:2px;"> 
                <div class="input-icon" data-aos="fade-left" data-aos-delay="1000">
                    <label  class="label-icon">
                        <i class="fa fa-list-alt"></i>
                    </label>
                    {% if form.cat_name.errors %}
                        <input class='form-control error' style="max-width:100%; width:80vw;" type='text' name='cat_name' placeholder=' Add category'>
                        <div class="invalid-feedback">
                            {% for error in form.cat_name.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        <input class='form-control' style="min-width:80vw; width:100%;" type='text' name='cat_name' placeholder=' Add Category'>
                    {% endif %}
                </div>
                <div class="input-icon">
                    <label  for="id_cat_img" class="btn btn-block">
                        <span><i class="fa fa-upload" aria-hidden="true"></i> Add Category Image</span>
                    </label>
                    <input type="file" name="cat_img" accept="image/*" id="id_cat_img">                                                
                </div>
            </div>

            <div class="form-group col-md-6">
                <div class="form-actions" data-aos="fade-left">
                    <button style="width:100px; margin-top:10px;" type="submit" class="btn btn-default">
                        <i class="fa fa-plus" aria-hidden="true"></i> Add
                    </button>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock content %}

myblog/templates/blog/categoryList.html
{% extends 'blog/index.html' %}
{% block content %}
<div class="container fs">
    <div class="team-grid">
        <div class="container">
            <div class="intro">
                <h1 class="text-center mb-4" style="font-size: 70px; font-weight: bolder;">Categories</h1>
            </div>
            <div class="row people" style="border-top: 2px solid #2c2c2c;">
                {% for category in cat %}
                <a class="col-md-4 col-lg-4 item" href="{% url 'cat' category %}">
                    <div class="box" style="background-image:url({{category.cat_img.url}})">
                        <div class="cover2 align-items-center d-flex justify-content-center">
                            <h1 class="name" style="font-size:60px;">{{category.cat_name}}</h1>                   
                        </div>
                    </div>
                </a> 
                {% endfor %}
                <a class="col-md-4 col-lg-4 item" href="{% url 'addcat' %}">
                    <div class="box" style="background:#776c6c;">
                        <div class="cover2 align-items-center d-flex justify-content-center">
                            <h1 class="name" style="font-size:60px;"><i class="fa fa-plus"></i><br>Add Category</h1>                   
                        </div>
                    </div>
                </a> 
            </div>
        </div>
    </div>
</div>
{% endblock content %}

myblog/templates/blog/update_post.html
{% extends 'blog/index.html' %}
{% load static %}
{% block content %}

<div class="login-clean container">
    <form data-aos="fade-left" enctype="multipart/form-data" data-aos-delay="600" method="POST" novalidate>
        {% csrf_token %}
        {{form.media}}
        <input type="hidden" name='id' value="{{post.pk}}">
        <div class="form-row">
            <div class="form-group col-md-6" style="margin-left:2px;"> 
                <div class="input-icon" data-aos="fade-left" data-aos-delay="1000">
                    <label  class="label-icon">
                        <i class="fa fa-user"></i>
                    </label>
                    {% if form.title.errors %}
                        <input class='form-control error' value="{{post.title}}" style="width:80vw;" type='text' name='title' placeholder='Title'>
                        <div class="invalid-feedback">
                            {% for error in form.title.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        <input class='form-control' value="{{post.title}}" style="width:80vw;" type='text' name='title' placeholder='Title'>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="form-group col-md-6"> 
            <div class="input-icon" style="width:300px;" data-aos="fade-left" data-aos-delay="1400">
                <label style="margin-top:10px;" for="id_thumbnail" class="btn-3 btn btn-default">
                    <span><i class="fa fa-upload" aria-hidden="true"></i> Choose Thumbnail Image</span>
                </label>
                <input type="file" name="thumbnail" accept="image/*" id="id_thumbnail">
            </div>
        </div>
        <div class="form-group"> 
            <div class="input-icon" data-aos="fade-left" data-aos-delay="1600">
                {{form.content}}
            </div>
        </div>

        <div class="form-group">
            <div class="form-actions" data-aos="fade-left">
                <button style="width:100px; margin:auto; float:none;" type="submit" class="btn btn-default">
                    <i class="fa fa-paper-plane" aria-hidden="true"></i> Update
                </button>
            </div>
        </div>
    </form>
  </div>
{% endblock content %}